# Copyright (C) 2015-2016 The CyanogenMod Project
# Copyright (C) 2017-2018 The LineageOS Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/huawei/scale/setup-makefiles.sh

PRODUCT_COPY_FILES += \
    vendor/huawei/scale/proprietary/vendor/lib/libstlport.so:system/vendor/lib/libstlport.so \
    vendor/huawei/scale/proprietary/vendor/bin/hw_test_diag:system/vendor/bin/hw_test_diag \
    vendor/huawei/scale/proprietary/vendor/bin/irsc_util:system/vendor/bin/irsc_util \
    vendor/huawei/scale/proprietary/vendor/bin/libqmi_oem_main:system/vendor/bin/libqmi_oem_main \
    vendor/huawei/scale/proprietary/vendor/bin/mm-qcamera-daemon:system/vendor/bin/mm-qcamera-daemon \
    vendor/huawei/scale/proprietary/vendor/bin/netmgrd:system/vendor/bin/netmgrd \
    vendor/huawei/scale/proprietary/vendor/bin/oeminfo_server:system/vendor/bin/oeminfo_server \
    vendor/huawei/scale/proprietary/vendor/bin/qmuxd:system/vendor/bin/qmuxd \
    vendor/huawei/scale/proprietary/vendor/bin/radish:system/vendor/bin/radish \
    vendor/huawei/scale/proprietary/vendor/bin/rmt_oeminfo:system/vendor/bin/rmt_oeminfo \
    vendor/huawei/scale/proprietary/vendor/bin/rmt_storage:system/vendor/bin/rmt_storage \
    vendor/huawei/scale/proprietary/vendor/etc/data/dsi_config.xml:system/vendor/etc/data/dsi_config.xml \
    vendor/huawei/scale/proprietary/vendor/etc/data/netmgr_config.xml:system/vendor/etc/data/netmgr_config.xml \
    vendor/huawei/scale/proprietary/vendor/firmware/SCALE_fts_fw.bin:system/vendor/firmware/SCALE_fts_fw.bin \
    vendor/huawei/scale/proprietary/vendor/firmware/SCALE_fw.bin:system/vendor/firmware/SCALE_fw.bin \
    vendor/huawei/scale/proprietary/vendor/firmware/SCALE_novatek_fw.bin:system/vendor/firmware/SCALE_novatek_fw.bin \
    vendor/huawei/scale/proprietary/vendor/firmware/SCALE_tianma_fw.img:system/vendor/firmware/SCALE_tianma_fw.img \
    vendor/huawei/scale/proprietary/vendor/firmware/Y538_fw.bin:system/vendor/firmware/Y538_fw.bin \
    vendor/huawei/scale/proprietary/vendor/firmware/cpp_firmware_v1_1_1.fw:system/vendor/firmware/cpp_firmware_v1_1_1.fw \
    vendor/huawei/scale/proprietary/vendor/firmware/cpp_firmware_v1_1_6.fw:system/vendor/firmware/cpp_firmware_v1_1_6.fw \
    vendor/huawei/scale/proprietary/vendor/firmware/cpp_firmware_v1_2_0.fw:system/vendor/firmware/cpp_firmware_v1_2_0.fw \
    vendor/huawei/scale/proprietary/vendor/firmware/cpp_firmware_v1_4_0.fw:system/vendor/firmware/cpp_firmware_v1_4_0.fw \
    vendor/huawei/scale/proprietary/vendor/firmware/leia_pfp_470.fw:system/vendor/firmware/leia_pfp_470.fw \
    vendor/huawei/scale/proprietary/vendor/firmware/leia_pm4_470.fw:system/vendor/firmware/leia_pm4_470.fw \
    vendor/huawei/scale/proprietary/vendor/etc/ons.bin:system/vendor/etc/ons.bin \
    vendor/huawei/scale/proprietary/vendor/etc/permissions/qcnvitems.xml:system/vendor/etc/permissions/qcnvitems.xml \
    vendor/huawei/scale/proprietary/vendor/etc/permissions/qcrilhook.xml:system/vendor/etc/permissions/qcrilhook.xml \
    vendor/huawei/scale/proprietary/vendor/framework/qcnvitems.jar:system/vendor/framework/qcnvitems.jar \
    vendor/huawei/scale/proprietary/vendor/framework/qcrilhook.jar:system/vendor/framework/qcrilhook.jar \
    vendor/huawei/scale/proprietary/vendor/lib/libdmd_report.so:system/vendor/lib/libdmd_report.so \
    vendor/huawei/scale/proprietary/vendor/lib/libmm-qcamera.so:system/vendor/lib/libmm-qcamera.so \
    vendor/huawei/scale/proprietary/vendor/lib/liboeminfo.so:system/vendor/lib/liboeminfo.so \
    vendor/huawei/scale/proprietary/vendor/lib/libqmi_nv_api.so:system/vendor/lib/libqmi_nv_api.so \
    vendor/huawei/scale/proprietary/vendor/etc/pdc_G620s_L01.txt:system/vendor/etc/pdc_G620s_L01.txt \
    vendor/huawei/scale/proprietary/vendor/lib/libactuator_dw9714.so:system/vendor/lib/libactuator_dw9714.so \
    vendor/huawei/scale/proprietary/vendor/lib/libactuator_dw9714_13p1ba.so:system/vendor/lib/libactuator_dw9714_13p1ba.so \
    vendor/huawei/scale/proprietary/vendor/lib/libactuator_dw9714_13p1ba_camcorder.so:system/vendor/lib/libactuator_dw9714_13p1ba_camcorder.so \
    vendor/huawei/scale/proprietary/vendor/lib/libactuator_dw9714_13p1ba_camera.so:system/vendor/lib/libactuator_dw9714_13p1ba_camera.so \
    vendor/huawei/scale/proprietary/vendor/lib/libactuator_dw9714_camcorder.so:system/vendor/lib/libactuator_dw9714_camcorder.so \
    vendor/huawei/scale/proprietary/vendor/lib/libactuator_dw9714_camera.so:system/vendor/lib/libactuator_dw9714_camera.so \
    vendor/huawei/scale/proprietary/vendor/lib/libactuator_dw9714_pc0fe.so:system/vendor/lib/libactuator_dw9714_pc0fe.so \
    vendor/huawei/scale/proprietary/vendor/lib/libactuator_dw9714_pc0fe_camcorder.so:system/vendor/lib/libactuator_dw9714_pc0fe_camcorder.so \
    vendor/huawei/scale/proprietary/vendor/lib/libactuator_dw9714_pc0fe_camera.so:system/vendor/lib/libactuator_dw9714_pc0fe_camera.so \
    vendor/huawei/scale/proprietary/vendor/lib/libactuator_dw9714_q13n04a.so:system/vendor/lib/libactuator_dw9714_q13n04a.so \
    vendor/huawei/scale/proprietary/vendor/lib/libactuator_dw9714_q13n04a_camcorder.so:system/vendor/lib/libactuator_dw9714_q13n04a_camcorder.so \
    vendor/huawei/scale/proprietary/vendor/lib/libactuator_dw9714_q13n04a_camera.so:system/vendor/lib/libactuator_dw9714_q13n04a_camera.so \
    vendor/huawei/scale/proprietary/vendor/lib/libactuator_dw9714_q13v04b.so:system/vendor/lib/libactuator_dw9714_q13v04b.so \
    vendor/huawei/scale/proprietary/vendor/lib/libactuator_dw9714_q13v04b_camcorder.so:system/vendor/lib/libactuator_dw9714_q13v04b_camcorder.so \
    vendor/huawei/scale/proprietary/vendor/lib/libactuator_dw9714_q13v04b_camera.so:system/vendor/lib/libactuator_dw9714_q13v04b_camera.so \
    vendor/huawei/scale/proprietary/vendor/lib/libactuator_imx219_liteon_3bab17.so:system/vendor/lib/libactuator_imx219_liteon_3bab17.so \
    vendor/huawei/scale/proprietary/vendor/lib/libactuator_imx219_liteon_3bab17_camcorder.so:system/vendor/lib/libactuator_imx219_liteon_3bab17_camcorder.so \
    vendor/huawei/scale/proprietary/vendor/lib/libactuator_imx219_liteon_3bab17_camera.so:system/vendor/lib/libactuator_imx219_liteon_3bab17_camera.so \
    vendor/huawei/scale/proprietary/vendor/lib/libactuator_imx219_ofilm_ohw8a04.so:system/vendor/lib/libactuator_imx219_ofilm_ohw8a04.so \
    vendor/huawei/scale/proprietary/vendor/lib/libactuator_imx219_ofilm_ohw8a04_camcorder.so:system/vendor/lib/libactuator_imx219_ofilm_ohw8a04_camcorder.so \
    vendor/huawei/scale/proprietary/vendor/lib/libactuator_imx219_ofilm_ohw8a04_camera.so:system/vendor/lib/libactuator_imx219_ofilm_ohw8a04_camera.so \
    vendor/huawei/scale/proprietary/vendor/lib/libactuator_ov8858_foxconn_sc1102.so:system/vendor/lib/libactuator_ov8858_foxconn_sc1102.so \
    vendor/huawei/scale/proprietary/vendor/lib/libactuator_ov8858_foxconn_sc1102_camcorder.so:system/vendor/lib/libactuator_ov8858_foxconn_sc1102_camcorder.so \
    vendor/huawei/scale/proprietary/vendor/lib/libactuator_ov8858_foxconn_sc1102_camera.so:system/vendor/lib/libactuator_ov8858_foxconn_sc1102_camera.so \
    vendor/huawei/scale/proprietary/vendor/lib/libcalmodule_akm.so:system/vendor/lib/libcalmodule_akm.so \
    vendor/huawei/scale/proprietary/vendor/lib/libcalmodule_gyroscope.so:system/vendor/lib/libcalmodule_gyroscope.so \
    vendor/huawei/scale/proprietary/vendor/lib/libchromatix_gc2355_ofilm_ohw2f03_common.so:system/vendor/lib/libchromatix_gc2355_ofilm_ohw2f03_common.so \
    vendor/huawei/scale/proprietary/vendor/lib/libchromatix_gc2355_ofilm_ohw2f03_default_video.so:system/vendor/lib/libchromatix_gc2355_ofilm_ohw2f03_default_video.so \
    vendor/huawei/scale/proprietary/vendor/lib/libchromatix_gc2355_ofilm_ohw2f03_preview.so:system/vendor/lib/libchromatix_gc2355_ofilm_ohw2f03_preview.so \
    vendor/huawei/scale/proprietary/vendor/lib/libchromatix_gc2355_ofilm_ohw2f03_snapshot.so:system/vendor/lib/libchromatix_gc2355_ofilm_ohw2f03_snapshot.so \
    vendor/huawei/scale/proprietary/vendor/lib/libchromatix_hi542_sunny_p5h04a_common.so:system/vendor/lib/libchromatix_hi542_sunny_p5h04a_common.so \
    vendor/huawei/scale/proprietary/vendor/lib/libchromatix_hi542_sunny_p5h04a_default_video.so:system/vendor/lib/libchromatix_hi542_sunny_p5h04a_default_video.so \
    vendor/huawei/scale/proprietary/vendor/lib/libchromatix_hi542_sunny_p5h04a_preview.so:system/vendor/lib/libchromatix_hi542_sunny_p5h04a_preview.so \
    vendor/huawei/scale/proprietary/vendor/lib/libchromatix_hi542_sunny_p5h04a_snapshot.so:system/vendor/lib/libchromatix_hi542_sunny_p5h04a_snapshot.so \
    vendor/huawei/scale/proprietary/vendor/lib/libchromatix_imx219_liteon_3bab17_common.so:system/vendor/lib/libchromatix_imx219_liteon_3bab17_common.so \
    vendor/huawei/scale/proprietary/vendor/lib/libchromatix_imx219_liteon_3bab17_default_video.so:system/vendor/lib/libchromatix_imx219_liteon_3bab17_default_video.so \
    vendor/huawei/scale/proprietary/vendor/lib/libchromatix_imx219_liteon_3bab17_liveshot.so:system/vendor/lib/libchromatix_imx219_liteon_3bab17_liveshot.so \
    vendor/huawei/scale/proprietary/vendor/lib/libchromatix_imx219_liteon_3bab17_preview.so:system/vendor/lib/libchromatix_imx219_liteon_3bab17_preview.so \
    vendor/huawei/scale/proprietary/vendor/lib/libchromatix_imx219_liteon_3bab17_snapshot.so:system/vendor/lib/libchromatix_imx219_liteon_3bab17_snapshot.so \
    vendor/huawei/scale/proprietary/vendor/lib/libchromatix_imx219_ofilm_ohw8a04_common.so:system/vendor/lib/libchromatix_imx219_ofilm_ohw8a04_common.so \
    vendor/huawei/scale/proprietary/vendor/lib/libchromatix_imx219_ofilm_ohw8a04_default_video.so:system/vendor/lib/libchromatix_imx219_ofilm_ohw8a04_default_video.so \
    vendor/huawei/scale/proprietary/vendor/lib/libchromatix_imx219_ofilm_ohw8a04_liveshot.so:system/vendor/lib/libchromatix_imx219_ofilm_ohw8a04_liveshot.so \
    vendor/huawei/scale/proprietary/vendor/lib/libchromatix_imx219_ofilm_ohw8a04_preview.so:system/vendor/lib/libchromatix_imx219_ofilm_ohw8a04_preview.so \
    vendor/huawei/scale/proprietary/vendor/lib/libchromatix_imx219_ofilm_ohw8a04_snapshot.so:system/vendor/lib/libchromatix_imx219_ofilm_ohw8a04_snapshot.so \
    vendor/huawei/scale/proprietary/vendor/lib/libchromatix_mt9d015_sunny_p2m19a_scale_common.so:system/vendor/lib/libchromatix_mt9d015_sunny_p2m19a_scale_common.so \
    vendor/huawei/scale/proprietary/vendor/lib/libchromatix_mt9d015_sunny_p2m19a_scale_default_video.so:system/vendor/lib/libchromatix_mt9d015_sunny_p2m19a_scale_default_video.so \
    vendor/huawei/scale/proprietary/vendor/lib/libchromatix_mt9d015_sunny_p2m19a_scale_preview.so:system/vendor/lib/libchromatix_mt9d015_sunny_p2m19a_scale_preview.so \
    vendor/huawei/scale/proprietary/vendor/lib/libchromatix_mt9d015_sunny_p2m19a_scale_snapshot.so:system/vendor/lib/libchromatix_mt9d015_sunny_p2m19a_scale_snapshot.so \
    vendor/huawei/scale/proprietary/vendor/lib/libchromatix_ov2680_byd_uhw8257m_scale_common.so:system/vendor/lib/libchromatix_ov2680_byd_uhw8257m_scale_common.so \
    vendor/huawei/scale/proprietary/vendor/lib/libchromatix_ov2680_byd_uhw8257m_scale_default_video.so:system/vendor/lib/libchromatix_ov2680_byd_uhw8257m_scale_default_video.so \
    vendor/huawei/scale/proprietary/vendor/lib/libchromatix_ov2680_byd_uhw8257m_scale_preview.so:system/vendor/lib/libchromatix_ov2680_byd_uhw8257m_scale_preview.so \
    vendor/huawei/scale/proprietary/vendor/lib/libchromatix_ov2680_byd_uhw8257m_scale_snapshot.so:system/vendor/lib/libchromatix_ov2680_byd_uhw8257m_scale_snapshot.so \
    vendor/huawei/scale/proprietary/vendor/lib/libchromatix_ov2680_ofilm_ohw2f01_scale_common.so:system/vendor/lib/libchromatix_ov2680_ofilm_ohw2f01_scale_common.so \
    vendor/huawei/scale/proprietary/vendor/lib/libchromatix_ov2680_ofilm_ohw2f01_scale_default_video.so:system/vendor/lib/libchromatix_ov2680_ofilm_ohw2f01_scale_default_video.so \
    vendor/huawei/scale/proprietary/vendor/lib/libchromatix_ov2680_ofilm_ohw2f01_scale_preview.so:system/vendor/lib/libchromatix_ov2680_ofilm_ohw2f01_scale_preview.so \
    vendor/huawei/scale/proprietary/vendor/lib/libchromatix_ov2680_ofilm_ohw2f01_scale_snapshot.so:system/vendor/lib/libchromatix_ov2680_ofilm_ohw2f01_scale_snapshot.so \
    vendor/huawei/scale/proprietary/vendor/lib/libchromatix_ov8858_foxconn_sc1102_common.so:system/vendor/lib/libchromatix_ov8858_foxconn_sc1102_common.so \
    vendor/huawei/scale/proprietary/vendor/lib/libchromatix_ov8858_foxconn_sc1102_default_video.so:system/vendor/lib/libchromatix_ov8858_foxconn_sc1102_default_video.so \
    vendor/huawei/scale/proprietary/vendor/lib/libchromatix_ov8858_foxconn_sc1102_hfr_120fps.so:system/vendor/lib/libchromatix_ov8858_foxconn_sc1102_hfr_120fps.so \
    vendor/huawei/scale/proprietary/vendor/lib/libchromatix_ov8858_foxconn_sc1102_hfr_60fps.so:system/vendor/lib/libchromatix_ov8858_foxconn_sc1102_hfr_60fps.so \
    vendor/huawei/scale/proprietary/vendor/lib/libchromatix_ov8858_foxconn_sc1102_hfr_90fps.so:system/vendor/lib/libchromatix_ov8858_foxconn_sc1102_hfr_90fps.so \
    vendor/huawei/scale/proprietary/vendor/lib/libchromatix_ov8858_foxconn_sc1102_liveshot.so:system/vendor/lib/libchromatix_ov8858_foxconn_sc1102_liveshot.so \
    vendor/huawei/scale/proprietary/vendor/lib/libchromatix_ov8858_foxconn_sc1102_preview.so:system/vendor/lib/libchromatix_ov8858_foxconn_sc1102_preview.so \
    vendor/huawei/scale/proprietary/vendor/lib/libchromatix_ov8858_foxconn_sc1102_snapshot.so:system/vendor/lib/libchromatix_ov8858_foxconn_sc1102_snapshot.so \
    vendor/huawei/scale/proprietary/vendor/lib/libchromatix_ov8858_foxconn_sc1102_zsl.so:system/vendor/lib/libchromatix_ov8858_foxconn_sc1102_zsl.so \
    vendor/huawei/scale/proprietary/vendor/lib/libchromatix_s5k4e1_foxconn_dc0301a_common.so:system/vendor/lib/libchromatix_s5k4e1_foxconn_dc0301a_common.so \
    vendor/huawei/scale/proprietary/vendor/lib/libchromatix_s5k4e1_foxconn_dc0301a_default_video.so:system/vendor/lib/libchromatix_s5k4e1_foxconn_dc0301a_default_video.so \
    vendor/huawei/scale/proprietary/vendor/lib/libchromatix_s5k4e1_foxconn_dc0301a_preview.so:system/vendor/lib/libchromatix_s5k4e1_foxconn_dc0301a_preview.so \
    vendor/huawei/scale/proprietary/vendor/lib/libchromatix_s5k4e1_foxconn_dc0301a_snapshot.so:system/vendor/lib/libchromatix_s5k4e1_foxconn_dc0301a_snapshot.so \
    vendor/huawei/scale/proprietary/vendor/lib/libconfigdb.so:system/vendor/lib/libconfigdb.so \
    vendor/huawei/scale/proprietary/vendor/lib/libdiag.so:system/vendor/lib/libdiag.so \
    vendor/huawei/scale/proprietary/vendor/lib/libdsi_netctrl.so:system/vendor/lib/libdsi_netctrl.so \
    vendor/huawei/scale/proprietary/vendor/lib/libdsutils.so:system/vendor/lib/libdsutils.so \
    vendor/huawei/scale/proprietary/vendor/lib/libidl.so:system/vendor/lib/libidl.so \
    vendor/huawei/scale/proprietary/vendor/lib/libjpegdhw.so:system/vendor/lib/libjpegdhw.so \
    vendor/huawei/scale/proprietary/vendor/lib/libjpegehw.so:system/vendor/lib/libjpegehw.so \
    vendor/huawei/scale/proprietary/vendor/lib/libmdmdetect.so:system/vendor/lib/libmdmdetect.so \
    vendor/huawei/scale/proprietary/vendor/lib/libmmcamera2_c2d_module.so:system/vendor/lib/libmmcamera2_c2d_module.so \
    vendor/huawei/scale/proprietary/vendor/lib/libmmcamera2_cpp_module.so:system/vendor/lib/libmmcamera2_cpp_module.so \
    vendor/huawei/scale/proprietary/vendor/lib/libmmcamera2_frame_algorithm.so:system/vendor/lib/libmmcamera2_frame_algorithm.so \
    vendor/huawei/scale/proprietary/vendor/lib/libmmcamera2_iface_modules.so:system/vendor/lib/libmmcamera2_iface_modules.so \
    vendor/huawei/scale/proprietary/vendor/lib/libmmcamera2_imglib_modules.so:system/vendor/lib/libmmcamera2_imglib_modules.so \
    vendor/huawei/scale/proprietary/vendor/lib/libmmcamera2_is.so:system/vendor/lib/libmmcamera2_is.so \
    vendor/huawei/scale/proprietary/vendor/lib/libmmcamera2_isp_modules.so:system/vendor/lib/libmmcamera2_isp_modules.so \
    vendor/huawei/scale/proprietary/vendor/lib/libmmcamera2_pproc_modules.so:system/vendor/lib/libmmcamera2_pproc_modules.so \
    vendor/huawei/scale/proprietary/vendor/lib/libmmcamera2_sensor_modules.so:system/vendor/lib/libmmcamera2_sensor_modules.so \
    vendor/huawei/scale/proprietary/vendor/lib/libmmcamera2_stats_algorithm.so:system/vendor/lib/libmmcamera2_stats_algorithm.so \
    vendor/huawei/scale/proprietary/vendor/lib/libmmcamera2_stats_modules.so:system/vendor/lib/libmmcamera2_stats_modules.so \
    vendor/huawei/scale/proprietary/vendor/lib/libmmcamera2_vpe_module.so:system/vendor/lib/libmmcamera2_vpe_module.so \
    vendor/huawei/scale/proprietary/vendor/lib/libmmcamera2_wnr_module.so:system/vendor/lib/libmmcamera2_wnr_module.so \
    vendor/huawei/scale/proprietary/vendor/lib/libmmcamera_faceproc.so:system/vendor/lib/libmmcamera_faceproc.so \
    vendor/huawei/scale/proprietary/vendor/lib/libmmcamera_gc2355_ofilm_ohw2f03.so:system/vendor/lib/libmmcamera_gc2355_ofilm_ohw2f03.so \
    vendor/huawei/scale/proprietary/vendor/lib/libmmcamera_hdr_gb_lib.so:system/vendor/lib/libmmcamera_hdr_gb_lib.so \
    vendor/huawei/scale/proprietary/vendor/lib/libmmcamera_hdr_lib.so:system/vendor/lib/libmmcamera_hdr_lib.so \
    vendor/huawei/scale/proprietary/vendor/lib/libmmcamera_hi256.so:system/vendor/lib/libmmcamera_hi256.so \
    vendor/huawei/scale/proprietary/vendor/lib/libmmcamera_hi542_sunny_p5h04a.so:system/vendor/lib/libmmcamera_hi542_sunny_p5h04a.so \
    vendor/huawei/scale/proprietary/vendor/lib/libmmcamera_imglib.so:system/vendor/lib/libmmcamera_imglib.so \
    vendor/huawei/scale/proprietary/vendor/lib/libmmcamera_imx219_liteon_3bab17.so:system/vendor/lib/libmmcamera_imx219_liteon_3bab17.so \
    vendor/huawei/scale/proprietary/vendor/lib/libmmcamera_imx219_ofilm_ohw8a04.so:system/vendor/lib/libmmcamera_imx219_ofilm_ohw8a04.so \
    vendor/huawei/scale/proprietary/vendor/lib/libmmcamera_mt9d015_sunny_p2m19a_scale.so:system/vendor/lib/libmmcamera_mt9d015_sunny_p2m19a_scale.so \
    vendor/huawei/scale/proprietary/vendor/lib/libmmcamera_mt9m114.so:system/vendor/lib/libmmcamera_mt9m114.so \
    vendor/huawei/scale/proprietary/vendor/lib/libmmcamera_ov2680_byd_uhw8257m_scale.so:system/vendor/lib/libmmcamera_ov2680_byd_uhw8257m_scale.so \
    vendor/huawei/scale/proprietary/vendor/lib/libmmcamera_ov2680_ofilm_ohw2f01_scale.so:system/vendor/lib/libmmcamera_ov2680_ofilm_ohw2f01_scale.so \
    vendor/huawei/scale/proprietary/vendor/lib/libmmcamera_ov8858_foxconn_sc1102.so:system/vendor/lib/libmmcamera_ov8858_foxconn_sc1102.so \
    vendor/huawei/scale/proprietary/vendor/lib/libmmcamera_s5k4e1_foxconn_dc0301a.so:system/vendor/lib/libmmcamera_s5k4e1_foxconn_dc0301a.so \
    vendor/huawei/scale/proprietary/vendor/lib/libmmcamera_sunny_p12v01m_eeprom.so:system/vendor/lib/libmmcamera_sunny_p12v01m_eeprom.so \
    vendor/huawei/scale/proprietary/vendor/lib/libmmcamera_sunny_q13v04b_eeprom.so:system/vendor/lib/libmmcamera_sunny_q13v04b_eeprom.so \
    vendor/huawei/scale/proprietary/vendor/lib/libmmcamera_sunrise_pc0fe_eeprom.so:system/vendor/lib/libmmcamera_sunrise_pc0fe_eeprom.so \
    vendor/huawei/scale/proprietary/vendor/lib/libmmcamera_tintless_algo.so:system/vendor/lib/libmmcamera_tintless_algo.so \
    vendor/huawei/scale/proprietary/vendor/lib/libmmcamera_tintless_bg_pca_algo.so:system/vendor/lib/libmmcamera_tintless_bg_pca_algo.so \
    vendor/huawei/scale/proprietary/vendor/lib/libmmcamera_truly_cm7700_eeprom.so:system/vendor/lib/libmmcamera_truly_cm7700_eeprom.so \
    vendor/huawei/scale/proprietary/vendor/lib/libmmcamera_tuning.so:system/vendor/lib/libmmcamera_tuning.so \
    vendor/huawei/scale/proprietary/vendor/lib/libmmcamera_wavelet_lib.so:system/vendor/lib/libmmcamera_wavelet_lib.so \
    vendor/huawei/scale/proprietary/vendor/lib/libmmipl.so:system/vendor/lib/libmmipl.so \
    vendor/huawei/scale/proprietary/vendor/lib/libmmjpeg.so:system/vendor/lib/libmmjpeg.so \
    vendor/huawei/scale/proprietary/vendor/lib/libmmqjpeg_codec.so:system/vendor/lib/libmmqjpeg_codec.so \
    vendor/huawei/scale/proprietary/vendor/lib/libnetmgr.so:system/vendor/lib/libnetmgr.so \
    vendor/huawei/scale/proprietary/vendor/lib/liboemcamera.so:system/vendor/lib/liboemcamera.so \
    vendor/huawei/scale/proprietary/vendor/lib/libperipheral_client.so:system/vendor/lib/libperipheral_client.so \
    vendor/huawei/scale/proprietary/vendor/lib/libqc-opt.so:system/vendor/lib/libqc-opt.so \
    vendor/huawei/scale/proprietary/vendor/lib/libqcamerasvr-c++.so:system/vendor/lib/libqcamerasvr-c++.so \
    vendor/huawei/scale/proprietary/vendor/lib/libqcci_legacy.so:system/vendor/lib/libqcci_legacy.so \
    vendor/huawei/scale/proprietary/vendor/lib/libqdi.so:system/vendor/lib/libqdi.so \
    vendor/huawei/scale/proprietary/vendor/lib/libqdp.so:system/vendor/lib/libqdp.so \
    vendor/huawei/scale/proprietary/vendor/lib/libqmi.so:system/vendor/lib/libqmi.so \
    vendor/huawei/scale/proprietary/vendor/lib/libqmi_cci.so:system/vendor/lib/libqmi_cci.so \
    vendor/huawei/scale/proprietary/vendor/lib/libqmi_client_helper.so:system/vendor/lib/libqmi_client_helper.so \
    vendor/huawei/scale/proprietary/vendor/lib/libqmi_client_qmux.so:system/vendor/lib/libqmi_client_qmux.so \
    vendor/huawei/scale/proprietary/vendor/lib/libqmi_common_so.so:system/vendor/lib/libqmi_common_so.so \
    vendor/huawei/scale/proprietary/vendor/lib/libqmi_csi.so:system/vendor/lib/libqmi_csi.so \
    vendor/huawei/scale/proprietary/vendor/lib/libqmi_encdec.so:system/vendor/lib/libqmi_encdec.so \
    vendor/huawei/scale/proprietary/vendor/lib/libqmiservices.so:system/vendor/lib/libqmiservices.so \
    vendor/huawei/scale/proprietary/vendor/lib/libqomx_jpegenc.so:system/vendor/lib/libqomx_jpegenc.so \
    vendor/huawei/scale/proprietary/vendor/lib/libril-qc-qmi-1.so:system/vendor/lib/libril-qc-qmi-1.so \
    vendor/huawei/scale/proprietary/vendor/lib/libril-qcril-hook-oem.so:system/vendor/lib/libril-qcril-hook-oem.so \
    vendor/huawei/scale/proprietary/vendor/lib/libsmemlog.so:system/vendor/lib/libsmemlog.so \
    vendor/huawei/scale/proprietary/vendor/lib/libsystem_health_mon.so:system/vendor/lib/libsystem_health_mon.so \
    vendor/huawei/scale/proprietary/vendor/lib/libxml.so:system/vendor/lib/libxml.so

PRODUCT_PACKAGES += \
    libhuawei_secure \
    liboeminfo_oem_api \
    libqmi_oem_api \
    shutdownlistener \
    qcrilmsgtunnel
