# Copyright (C) 2015-2016 The CyanogenMod Project
# Copyright (C) 2017 The LineageOS Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/huawei/scale/setup-makefiles.sh


# Sensors
#PRODUCT_COPY_FILES += \
#    vendor/huawei/scale/proprietary/lib/sensors.msm8909.so:system/lib/hw/sensors.msm8909.so \
#    vendor/huawei/scale/proprietary/vendor/lib/libcalmodule_common.so:system/vendor/lib/libcalmodule_common.so \
#    vendor/huawei/scale/proprietary/vendor/lib/libcalmodule_gyroscope.so:system/vendor/lib/libcalmodule_gyroscope.so

PRODUCT_COPY_FILES += \
    vendor/huawei/scale/proprietary/bin/mm-qcamera-daemon:system/bin/mm-qcamera-daemon \
    vendor/huawei/scale/proprietary/etc/firmware/venus.b00:system/etc/firmware/venus.b00 \
    vendor/huawei/scale/proprietary/etc/firmware/venus.b01:system/etc/firmware/venus.b01 \
    vendor/huawei/scale/proprietary/etc/firmware/venus.b02:system/etc/firmware/venus.b02 \
    vendor/huawei/scale/proprietary/etc/firmware/venus.b03:system/etc/firmware/venus.b03 \
    vendor/huawei/scale/proprietary/etc/firmware/venus.b04:system/etc/firmware/venus.b04 \
    vendor/huawei/scale/proprietary/etc/firmware/venus.mbn:system/etc/firmware/venus.mbn \
    vendor/huawei/scale/proprietary/etc/firmware/venus.mdt:system/etc/firmware/venus.mdt \
    vendor/huawei/scale/proprietary/lib/libdmd_report.so:system/lib/libdmd_report.so \
    vendor/huawei/scale/proprietary/lib/libmmcamera_interface.so:system/lib/libmmcamera_interface.so \
    vendor/huawei/scale/proprietary/lib/libmmjpeg_interface.so:system/lib/libmmjpeg_interface.so \
    vendor/huawei/scale/proprietary/lib/libqdMetaData.so:system/lib/libqdMetaData.so \
    vendor/huawei/scale/proprietary/lib/libOmxSwVencMpeg4.so:system/lib/libOmxSwVencMpeg4.so \
    vendor/huawei/scale/proprietary/vendor/lib/libMpeg4SwEncoder.so:system/vendor/lib/libMpeg4SwEncoder.so \
    vendor/huawei/scale/proprietary/lib/libqomx_core.so:system/lib/libqomx_core.so \
    vendor/huawei/scale/proprietary/vendor/lib/libDivxDrm.so:system/vendor/lib/libDivxDrm.so \
    vendor/huawei/scale/proprietary/vendor/lib/libactuator_dw9714.so:system/vendor/lib/libactuator_dw9714.so \
    vendor/huawei/scale/proprietary/vendor/lib/libactuator_dw9714_13p1ba.so:system/vendor/lib/libactuator_dw9714_13p1ba.so \
    vendor/huawei/scale/proprietary/vendor/lib/libactuator_dw9714_13p1ba_camcorder.so:system/vendor/lib/libactuator_dw9714_13p1ba_camcorder.so \
    vendor/huawei/scale/proprietary/vendor/lib/libactuator_dw9714_13p1ba_camera.so:system/vendor/lib/libactuator_dw9714_13p1ba_camera.so \
    vendor/huawei/scale/proprietary/vendor/lib/libactuator_dw9714_camcorder.so:system/vendor/lib/libactuator_dw9714_camcorder.so \
    vendor/huawei/scale/proprietary/vendor/lib/libactuator_dw9714_camera.so:system/vendor/lib/libactuator_dw9714_camera.so \
    vendor/huawei/scale/proprietary/vendor/lib/libactuator_dw9714_pc0fe.so:system/vendor/lib/libactuator_dw9714_pc0fe.so \
    vendor/huawei/scale/proprietary/vendor/lib/libactuator_dw9714_pc0fe_camcorder.so:system/vendor/lib/libactuator_dw9714_pc0fe_camcorder.so \
    vendor/huawei/scale/proprietary/vendor/lib/libactuator_dw9714_pc0fe_camera.so:system/vendor/lib/libactuator_dw9714_pc0fe_camera.so \
    vendor/huawei/scale/proprietary/vendor/lib/libactuator_dw9714_q13n04a.so:system/vendor/lib/libactuator_dw9714_q13n04a.so \
    vendor/huawei/scale/proprietary/vendor/lib/libactuator_dw9714_q13n04a_camcorder.so:system/vendor/lib/libactuator_dw9714_q13n04a_camcorder.so \
    vendor/huawei/scale/proprietary/vendor/lib/libactuator_dw9714_q13n04a_camera.so:system/vendor/lib/libactuator_dw9714_q13n04a_camera.so \
    vendor/huawei/scale/proprietary/vendor/lib/libactuator_dw9714_q13v04b.so:system/vendor/lib/libactuator_dw9714_q13v04b.so \
    vendor/huawei/scale/proprietary/vendor/lib/libactuator_dw9714_q13v04b_camcorder.so:system/vendor/lib/libactuator_dw9714_q13v04b_camcorder.so \
    vendor/huawei/scale/proprietary/vendor/lib/libactuator_dw9714_q13v04b_camera.so:system/vendor/lib/libactuator_dw9714_q13v04b_camera.so \
    vendor/huawei/scale/proprietary/vendor/lib/libactuator_imx219_liteon_3bab17.so:system/vendor/lib/libactuator_imx219_liteon_3bab17.so \
    vendor/huawei/scale/proprietary/vendor/lib/libactuator_imx219_liteon_3bab17_camcorder.so:system/vendor/lib/libactuator_imx219_liteon_3bab17_camcorder.so \
    vendor/huawei/scale/proprietary/vendor/lib/libactuator_imx219_liteon_3bab17_camera.so:system/vendor/lib/libactuator_imx219_liteon_3bab17_camera.so \
    vendor/huawei/scale/proprietary/vendor/lib/libactuator_imx219_ofilm_ohw8a04.so:system/vendor/lib/libactuator_imx219_ofilm_ohw8a04.so \
    vendor/huawei/scale/proprietary/vendor/lib/libactuator_imx219_ofilm_ohw8a04_camcorder.so:system/vendor/lib/libactuator_imx219_ofilm_ohw8a04_camcorder.so \
    vendor/huawei/scale/proprietary/vendor/lib/libactuator_imx219_ofilm_ohw8a04_camera.so:system/vendor/lib/libactuator_imx219_ofilm_ohw8a04_camera.so \
    vendor/huawei/scale/proprietary/vendor/lib/libactuator_ov8858_foxconn_sc1102.so:system/vendor/lib/libactuator_ov8858_foxconn_sc1102.so \
    vendor/huawei/scale/proprietary/vendor/lib/libactuator_ov8858_foxconn_sc1102_camcorder.so:system/vendor/lib/libactuator_ov8858_foxconn_sc1102_camcorder.so \
    vendor/huawei/scale/proprietary/vendor/lib/libactuator_ov8858_foxconn_sc1102_camera.so:system/vendor/lib/libactuator_ov8858_foxconn_sc1102_camera.so \
    vendor/huawei/scale/proprietary/vendor/lib/libchromatix_gc2355_ofilm_ohw2f03_common.so:system/vendor/lib/libchromatix_gc2355_ofilm_ohw2f03_common.so \
    vendor/huawei/scale/proprietary/vendor/lib/libchromatix_gc2355_ofilm_ohw2f03_default_video.so:system/vendor/lib/libchromatix_gc2355_ofilm_ohw2f03_default_video.so \
    vendor/huawei/scale/proprietary/vendor/lib/libchromatix_gc2355_ofilm_ohw2f03_preview.so:system/vendor/lib/libchromatix_gc2355_ofilm_ohw2f03_preview.so \
    vendor/huawei/scale/proprietary/vendor/lib/libchromatix_gc2355_ofilm_ohw2f03_snapshot.so:system/vendor/lib/libchromatix_gc2355_ofilm_ohw2f03_snapshot.so \
    vendor/huawei/scale/proprietary/vendor/lib/libchromatix_hi542_sunny_p5h04a_common.so:system/vendor/lib/libchromatix_hi542_sunny_p5h04a_common.so \
    vendor/huawei/scale/proprietary/vendor/lib/libchromatix_hi542_sunny_p5h04a_default_video.so:system/vendor/lib/libchromatix_hi542_sunny_p5h04a_default_video.so \
    vendor/huawei/scale/proprietary/vendor/lib/libchromatix_hi542_sunny_p5h04a_preview.so:system/vendor/lib/libchromatix_hi542_sunny_p5h04a_preview.so \
    vendor/huawei/scale/proprietary/vendor/lib/libchromatix_hi542_sunny_p5h04a_snapshot.so:system/vendor/lib/libchromatix_hi542_sunny_p5h04a_snapshot.so \
    vendor/huawei/scale/proprietary/vendor/lib/libchromatix_imx219_liteon_3bab17_common.so:system/vendor/lib/libchromatix_imx219_liteon_3bab17_common.so \
    vendor/huawei/scale/proprietary/vendor/lib/libchromatix_imx219_liteon_3bab17_default_video.so:system/vendor/lib/libchromatix_imx219_liteon_3bab17_default_video.so \
    vendor/huawei/scale/proprietary/vendor/lib/libchromatix_imx219_liteon_3bab17_liveshot.so:system/vendor/lib/libchromatix_imx219_liteon_3bab17_liveshot.so \
    vendor/huawei/scale/proprietary/vendor/lib/libchromatix_imx219_liteon_3bab17_preview.so:system/vendor/lib/libchromatix_imx219_liteon_3bab17_preview.so \
    vendor/huawei/scale/proprietary/vendor/lib/libchromatix_imx219_liteon_3bab17_snapshot.so:system/vendor/lib/libchromatix_imx219_liteon_3bab17_snapshot.so \
    vendor/huawei/scale/proprietary/vendor/lib/libchromatix_imx219_ofilm_ohw8a04_common.so:system/vendor/lib/libchromatix_imx219_ofilm_ohw8a04_common.so \
    vendor/huawei/scale/proprietary/vendor/lib/libchromatix_imx219_ofilm_ohw8a04_default_video.so:system/vendor/lib/libchromatix_imx219_ofilm_ohw8a04_default_video.so \
    vendor/huawei/scale/proprietary/vendor/lib/libchromatix_imx219_ofilm_ohw8a04_liveshot.so:system/vendor/lib/libchromatix_imx219_ofilm_ohw8a04_liveshot.so \
    vendor/huawei/scale/proprietary/vendor/lib/libchromatix_imx219_ofilm_ohw8a04_preview.so:system/vendor/lib/libchromatix_imx219_ofilm_ohw8a04_preview.so \
    vendor/huawei/scale/proprietary/vendor/lib/libchromatix_imx219_ofilm_ohw8a04_snapshot.so:system/vendor/lib/libchromatix_imx219_ofilm_ohw8a04_snapshot.so \
    vendor/huawei/scale/proprietary/vendor/lib/libchromatix_mt9d015_sunny_p2m19a_scale_common.so:system/vendor/lib/libchromatix_mt9d015_sunny_p2m19a_scale_common.so \
    vendor/huawei/scale/proprietary/vendor/lib/libchromatix_mt9d015_sunny_p2m19a_scale_default_video.so:system/vendor/lib/libchromatix_mt9d015_sunny_p2m19a_scale_default_video.so \
    vendor/huawei/scale/proprietary/vendor/lib/libchromatix_mt9d015_sunny_p2m19a_scale_preview.so:system/vendor/lib/libchromatix_mt9d015_sunny_p2m19a_scale_preview.so \
    vendor/huawei/scale/proprietary/vendor/lib/libchromatix_mt9d015_sunny_p2m19a_scale_snapshot.so:system/vendor/lib/libchromatix_mt9d015_sunny_p2m19a_scale_snapshot.so \
    vendor/huawei/scale/proprietary/vendor/lib/libchromatix_ov2680_byd_uhw8257m_scale_common.so:system/vendor/lib/libchromatix_ov2680_byd_uhw8257m_scale_common.so \
    vendor/huawei/scale/proprietary/vendor/lib/libchromatix_ov2680_byd_uhw8257m_scale_default_video.so:system/vendor/lib/libchromatix_ov2680_byd_uhw8257m_scale_default_video.so \
    vendor/huawei/scale/proprietary/vendor/lib/libchromatix_ov2680_byd_uhw8257m_scale_preview.so:system/vendor/lib/libchromatix_ov2680_byd_uhw8257m_scale_preview.so \
    vendor/huawei/scale/proprietary/vendor/lib/libchromatix_ov2680_byd_uhw8257m_scale_snapshot.so:system/vendor/lib/libchromatix_ov2680_byd_uhw8257m_scale_snapshot.so \
    vendor/huawei/scale/proprietary/vendor/lib/libchromatix_ov2680_ofilm_ohw2f01_scale_common.so:system/vendor/lib/libchromatix_ov2680_ofilm_ohw2f01_scale_common.so \
    vendor/huawei/scale/proprietary/vendor/lib/libchromatix_ov2680_ofilm_ohw2f01_scale_default_video.so:system/vendor/lib/libchromatix_ov2680_ofilm_ohw2f01_scale_default_video.so \
    vendor/huawei/scale/proprietary/vendor/lib/libchromatix_ov2680_ofilm_ohw2f01_scale_preview.so:system/vendor/lib/libchromatix_ov2680_ofilm_ohw2f01_scale_preview.so \
    vendor/huawei/scale/proprietary/vendor/lib/libchromatix_ov2680_ofilm_ohw2f01_scale_snapshot.so:system/vendor/lib/libchromatix_ov2680_ofilm_ohw2f01_scale_snapshot.so \
    vendor/huawei/scale/proprietary/vendor/lib/libchromatix_ov8858_foxconn_sc1102_common.so:system/vendor/lib/libchromatix_ov8858_foxconn_sc1102_common.so \
    vendor/huawei/scale/proprietary/vendor/lib/libchromatix_ov8858_foxconn_sc1102_default_video.so:system/vendor/lib/libchromatix_ov8858_foxconn_sc1102_default_video.so \
    vendor/huawei/scale/proprietary/vendor/lib/libchromatix_ov8858_foxconn_sc1102_hfr_120fps.so:system/vendor/lib/libchromatix_ov8858_foxconn_sc1102_hfr_120fps.so \
    vendor/huawei/scale/proprietary/vendor/lib/libchromatix_ov8858_foxconn_sc1102_hfr_60fps.so:system/vendor/lib/libchromatix_ov8858_foxconn_sc1102_hfr_60fps.so \
    vendor/huawei/scale/proprietary/vendor/lib/libchromatix_ov8858_foxconn_sc1102_hfr_90fps.so:system/vendor/lib/libchromatix_ov8858_foxconn_sc1102_hfr_90fps.so \
    vendor/huawei/scale/proprietary/vendor/lib/libchromatix_ov8858_foxconn_sc1102_liveshot.so:system/vendor/lib/libchromatix_ov8858_foxconn_sc1102_liveshot.so \
    vendor/huawei/scale/proprietary/vendor/lib/libchromatix_ov8858_foxconn_sc1102_preview.so:system/vendor/lib/libchromatix_ov8858_foxconn_sc1102_preview.so \
    vendor/huawei/scale/proprietary/vendor/lib/libchromatix_ov8858_foxconn_sc1102_snapshot.so:system/vendor/lib/libchromatix_ov8858_foxconn_sc1102_snapshot.so \
    vendor/huawei/scale/proprietary/vendor/lib/libchromatix_ov8858_foxconn_sc1102_zsl.so:system/vendor/lib/libchromatix_ov8858_foxconn_sc1102_zsl.so \
    vendor/huawei/scale/proprietary/vendor/lib/libchromatix_s5k4e1_foxconn_dc0301a_common.so:system/vendor/lib/libchromatix_s5k4e1_foxconn_dc0301a_common.so \
    vendor/huawei/scale/proprietary/vendor/lib/libchromatix_s5k4e1_foxconn_dc0301a_default_video.so:system/vendor/lib/libchromatix_s5k4e1_foxconn_dc0301a_default_video.so \
    vendor/huawei/scale/proprietary/vendor/lib/libchromatix_s5k4e1_foxconn_dc0301a_preview.so:system/vendor/lib/libchromatix_s5k4e1_foxconn_dc0301a_preview.so \
    vendor/huawei/scale/proprietary/vendor/lib/libchromatix_s5k4e1_foxconn_dc0301a_snapshot.so:system/vendor/lib/libchromatix_s5k4e1_foxconn_dc0301a_snapshot.so \
    vendor/huawei/scale/proprietary/vendor/lib/libmmcamera2_c2d_module.so:system/vendor/lib/libmmcamera2_c2d_module.so \
    vendor/huawei/scale/proprietary/vendor/lib/libmmcamera2_frame_algorithm.so:system/vendor/lib/libmmcamera2_frame_algorithm.so \
    vendor/huawei/scale/proprietary/vendor/lib/libmmcamera2_iface_modules.so:system/vendor/lib/libmmcamera2_iface_modules.so \
    vendor/huawei/scale/proprietary/vendor/lib/libmmcamera2_imglib_modules.so:system/vendor/lib/libmmcamera2_imglib_modules.so \
    vendor/huawei/scale/proprietary/vendor/lib/libmmcamera2_is.so:system/vendor/lib/libmmcamera2_is.so \
    vendor/huawei/scale/proprietary/vendor/lib/libmmcamera2_isp_modules.so:system/vendor/lib/libmmcamera2_isp_modules.so \
    vendor/huawei/scale/proprietary/vendor/lib/libmmcamera2_pproc_modules.so:system/vendor/lib/libmmcamera2_pproc_modules.so \
    vendor/huawei/scale/proprietary/vendor/lib/libmmcamera2_sensor_modules.so:system/vendor/lib/libmmcamera2_sensor_modules.so \
    vendor/huawei/scale/proprietary/vendor/lib/libmmcamera2_stats_algorithm.so:system/vendor/lib/libmmcamera2_stats_algorithm.so \
    vendor/huawei/scale/proprietary/vendor/lib/libmmcamera2_stats_modules.so:system/vendor/lib/libmmcamera2_stats_modules.so \
    vendor/huawei/scale/proprietary/vendor/lib/libmmcamera2_wnr_module.so:system/vendor/lib/libmmcamera2_wnr_module.so \
    vendor/huawei/scale/proprietary/vendor/lib/libmmcamera_faceproc.so:system/vendor/lib/libmmcamera_faceproc.so \
    vendor/huawei/scale/proprietary/vendor/lib/libmmcamera_gc2355_ofilm_ohw2f03.so:system/vendor/lib/libmmcamera_gc2355_ofilm_ohw2f03.so \
    vendor/huawei/scale/proprietary/vendor/lib/libmmcamera_hi256.so:system/vendor/lib/libmmcamera_hi256.so \
    vendor/huawei/scale/proprietary/vendor/lib/libmmcamera_hi542_sunny_p5h04a.so:system/vendor/lib/libmmcamera_hi542_sunny_p5h04a.so \
    vendor/huawei/scale/proprietary/vendor/lib/libmmcamera_imx219_liteon_3bab17.so:system/vendor/lib/libmmcamera_imx219_liteon_3bab17.so \
    vendor/huawei/scale/proprietary/vendor/lib/libmmcamera_imx219_ofilm_ohw8a04.so:system/vendor/lib/libmmcamera_imx219_ofilm_ohw8a04.so \
    vendor/huawei/scale/proprietary/vendor/lib/libmmcamera_mt9d015_sunny_p2m19a_scale.so:system/vendor/lib/libmmcamera_mt9d015_sunny_p2m19a_scale.so \
    vendor/huawei/scale/proprietary/vendor/lib/libmmcamera_mt9m114.so:system/vendor/lib/libmmcamera_mt9m114.so \
    vendor/huawei/scale/proprietary/vendor/lib/libmmcamera_ov2680_byd_uhw8257m_scale.so:system/vendor/lib/libmmcamera_ov2680_byd_uhw8257m_scale.so \
    vendor/huawei/scale/proprietary/vendor/lib/libmmcamera_ov2680_ofilm_ohw2f01_scale.so:system/vendor/lib/libmmcamera_ov2680_ofilm_ohw2f01_scale.so \
    vendor/huawei/scale/proprietary/vendor/lib/libmmcamera_ov8858_foxconn_sc1102.so:system/vendor/lib/libmmcamera_ov8858_foxconn_sc1102.so \
    vendor/huawei/scale/proprietary/vendor/lib/libmmcamera_s5k4e1_foxconn_dc0301a.so:system/vendor/lib/libmmcamera_s5k4e1_foxconn_dc0301a.so \
    vendor/huawei/scale/proprietary/vendor/lib/libmmcamera_sunny_p12v01m_eeprom.so:system/vendor/lib/libmmcamera_sunny_p12v01m_eeprom.so \
    vendor/huawei/scale/proprietary/vendor/lib/libmmcamera_sunny_q13v04b_eeprom.so:system/vendor/lib/libmmcamera_sunny_q13v04b_eeprom.so \
    vendor/huawei/scale/proprietary/vendor/lib/libmmcamera_sunrise_pc0fe_eeprom.so:system/vendor/lib/libmmcamera_sunrise_pc0fe_eeprom.so \
    vendor/huawei/scale/proprietary/vendor/lib/libmmcamera_truly_cm7700_eeprom.so:system/vendor/lib/libmmcamera_truly_cm7700_eeprom.so \
    vendor/huawei/scale/proprietary/vendor/lib/liboemcamera.so:system/vendor/lib/liboemcamera.so \
    vendor/huawei/scale/proprietary/vendor/lib/libuiblur.so:system/vendor/lib/libuiblur.so
